version: '3.9'

services: 
    nginx:
        build: 
            dockerfile: Dockerfile
            context: ./nginx
        container_name: nginx
        image: danilocostaolist/nginx
        ports: 
            - "8080:80"
        working_dir: /etc/nginx/
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./static:/var/www/static/
        networks: 
            - prod
        depends_on:
            - app

    app:
        build: 
            dockerfile: Dockerfile
            context: .
        image: danilocostaolist/ts-test-nginx
        container_name: app
        ports: 
            - "8000:8000"
        command: bash -f ./scripts/run.sh
        volumes: 
            - .:/var/www
        working_dir: /var/www
        restart: always
        networks: 
            - prod            

networks: 
    prod:
        driver: bridge
